### PR TITLE
Added Brazilian Portuguese (pt-br) translation.

### PR DESCRIPTION
**Pull request by GabrielMottaDev**

### CODE REVIEW

**Review by nickuc — APPROVED** [review]

**Comment by linsaftw** [comment]
Hi, are you sure this is automatically loading when player joins with pt-br language? because i think minecraft uses PT_BR and not "pt-br" like you wrote in the file.

**Comment by GabrielMottaDev** [comment]
Hi, i implemented the translation, but i was using with the "lang" begin explicit in "config.yml"
Now, knowing about this automatization i decided to take a look.
And after some tests at the methods used to build the message (like that part):

'
String locale = proxiedPlayer.getLocale().toLanguageTag();
// Outputs testeds: ["pt-BR", "en-US"]
'

I changed to "pt-BR" and worked perfectly.
The value is case sensitive, and "_" dont work, maybe in some point of the code the minecraft interprets as "pt_br". But accessing the information like the example above, shows that the syntax is different int this case.
Maybe if doing changes in the class "PlaceholderModule.java", we can modify the final syntax used by config (but is pointless..)

The important is: now, after this change it is working fine

**Comment by linsaftw** [comment]
And how about using pt instead of pt-br to allow for more people to understand? or is written differently?

I will work on improve how locales are get from the message file :)

**Comment by GabrielMottaDev** [comment]
Have some differences beetween pt and pt-br.
Its complicated to explaine.. but think that way: when a portuguese speaker from europe reads an translation made for brazilian portuguese, if doesnt have any complex different words he can understand

**Comment by GabrielMottaDev** [comment]
I mean.. you can tell for witch one the messages are written for, but can understand the meaning.
Its like if its an incomplete translation.

For short, its written differently depending on the case.
I added a new commit with a translation for pt-PT (a friend from Portugal helped me, so they are very well located).

**Pull request merged**
