### PR TITLE
Some optimizations, RateLimitModule fix.

### PR DESCRIPTION
**Pull request by hakanguzelgulgen**
- I realize that there is no enabled check for RateLimitModule. I made a new function to check it.
- Some changes.

### CODE REVIEW

**Review by linsaftw — CHANGES_REQUESTED** [review]
Hi, please remove the changes to the config. Why were they made? (Removing /reg, /register, /login and added /g? What is /g?) And please make "Connection connection" on the meetCheck method final to keep the style of the code.

**Comment by hakanguzelgulgen** [comment]
RateLimitModule is done. Check 'Configuration update' commit if you still don't want just inform me.

**Comment by linsaftw** [comment]
> RateLimitModule is done. Check 'Configuration update' commit if you still don't want just inform me.

That doesn't seem correct; It would be better to just add commands like "/login " because otherwise it would detect with "/l" stuff like "/lag" and stuff like that...

**Comment by linsaftw** [comment]
I mean, with an space at the end so they dont end up detecting stuff that isnt required. for example "/l " wont detect "/lego"

**Comment by hakanguzelgulgen** [comment]
Oh got it. Check now.

**Pull request merged**
